name       : python-entrypoints
version    : 0.2.3
release    : 1
source     :
    - https://pypi.python.org/packages/27/e8/607697e6ab8a961fc0b141a97ea4ce72cd9c9e264adeb0669f6d194aa626/entrypoints-0.2.3.tar.gz : d2d587dde06f99545fb13a383d2cd336a8ff1f359c5839ce3a64c917d10c029f
license    : MIT
component  : programming.python
summary    : Discover and load entry points from installed packages.
description: |
    Discover and load entry points from installed packages.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - python-configparser
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
