name       : python-entrypoints
version    : '0.3'
release    : 4
source     :
    - https://files.pythonhosted.org/packages/b4/ef/063484f1f9ba3081e920ec9972c96664e2edb9fdc3d8669b0e3b8fc0ad7c/entrypoints-0.3.tar.gz : c70dd71abe5a8c85e55e12c19bd91ccfeec11a6e99044204511f9ed547d48451
license    : MIT
component  : programming.python
summary    : Discover and load entry points from installed packages.
description: |
    Discover and load entry points from installed packages.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-configparser
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
